[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
